### ISSUE TITLE
Cannot import finpie in Anaconda Spyder

### ISSUE THREAD

**Issue by jclynch86** [peterlacour/finpie#11]
After taking a while to pip intall finpie, I tried to import it into Spyder and I got the following error. Any help about how to deal with this would be very appreciated.

import finpie
Traceback (most recent call last):

  File "<ipython-input-6-a4034cd1c351>", line 1, in <module>
    import finpie

  File "C:\Users\lynch.643\.conda\envs\truebase\lib\site-packages\finpie\__init__.py", line 43, in <module>
    from finpie.price_data.price_data import historical_prices

  File "C:\Users\lynch.643\.conda\envs\truebase\lib\site-packages\finpie\price_data\__init__.py", line 26, in <module>
    from .price_data import historical_prices, yahoo_option_chain, cboe_option_chain

  File "C:\Users\lynch.643\.conda\envs\truebase\lib\site-packages\finpie\price_data\price_data.py", line 33, in <module>
    import dask.dataframe as dd

  File "C:\Users\lynch.643\.conda\envs\truebase\lib\site-packages\dask\dataframe\__init__.py", line 2, in <module>
    from .core import (

  File "C:\Users\lynch.643\.conda\envs\truebase\lib\site-packages\dask\dataframe\core.py", line 25, in <module>
    from .. import array as da

  File "C:\Users\lynch.643\.conda\envs\truebase\lib\site-packages\dask\array\__init__.py", line 218, in <module>
    from . import random, linalg, overlap, fft, backends

  File "C:\Users\lynch.643\.conda\envs\truebase\lib\site-packages\dask\array\random.py", line 463, in <module>
    _state = RandomState()

  File "C:\Users\lynch.643\.conda\envs\truebase\lib\site-packages\dask\array\random.py", line 72, in __init__
    self._numpy_state = np.random.RandomState(seed)

  File "mtrand.pyx", line 180, in numpy.random.mtrand.RandomState.__init__

  File "_mt19937.pyx", line 130, in numpy.random._mt19937.MT19937.__init__

  File "C:\Users\lynch.643\.conda\envs\truebase\lib\contextlib.py", line 73, in inner
    with self._recreate_cm():

  File "C:\Users\lynch.643\.conda\envs\truebase\lib\site-packages\numpy\core\_ufunc_config.py", line 444, in __enter__
    def _setdef():

  File "C:\Users\lynch.643\.conda\envs\truebase\lib\site-packages\numpy\core\_ufunc_config.py", line 308, in seterrcall
    raise ValueError("Only callable can be used as callback")

ValueError: Only callable can be used as callback

**Comment by peterlacour** [comment]
Hey sorry for the late reply

I am not sure what is causing this issue. This could be a problem with the dask package  / installation at first sight. You could try re-installing dask separately or just try to reinstall this package..
