### ISSUE TITLE
historical_prices() fails arbitrarily

### ISSUE THREAD

**Issue by Ginsterfeld** [peterlacour/finpie#18]
Hi @peterlacour.

While using recursively the function `historical_prices` to obtain historic prices of a list of company tickers, sometimes a company's ticker blocks the whole iteration throwing the following exception:

`company_price_log = finpie.price_data.historical_prices('DG')
Traceback (most recent call last):
  File "y:\Carpeta de Jose\dev\scarwell\git\data_extraction\Extraction_prices_ratios.py", line 50, in <module>
    company_price_log = finpie.price_data.historical_prices(ticker)
  File "C:\Users\J_A_A\AppData\Local\Programs\Python\Python39\lib\site-packages\finpie\price_data\price_data.py", line 66, in historical_prices
    df = pd.read_csv(StringIO(r))
  File "C:\Users\J_A_A\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\J_A_A\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\parsers.py", line 468, in _read
    return parser.read(nrows)
  File "C:\Users\J_A_A\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "C:\Users\J_A_A\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas\_libs\parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas\_libs\parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas\_libs\parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas\_libs\parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas\_libs\parsers.pyx", line 1951, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 4, saw 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\J_A_A\.vscode\extensions\ms-python.python-2021.8.1105858891\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_vars.py", line 419, in evaluate_expression
    compiled = compile(_expression_to_evaluate(expression), '<string>', 'eval')
  File "<string>", line 1
    company_price_log = finpie.price_data.historical_prices('DG')
                      ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\J_A_A\AppData\Local\Programs\Python\Python39\lib\site-packages\finpie\price_data\price_data.py", line 66, in historical_prices
    df = pd.read_csv(StringIO(r))
  File "C:\Users\J_A_A\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\J_A_A\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\parsers.py", line 468, in _read
    return parser.read(nrows)
  File "C:\Users\J_A_A\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "C:\Users\J_A_A\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas\_libs\parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas\_libs\parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas\_libs\parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas\_libs\parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas\_libs\parsers.pyx", line 1951, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 4, saw 2`

Even if I handle this exception ignoring it for example, next calls to this function with different ticker names fail as well. The point in which this begins to fail is arbitrary and can happen any time.

Best regards,
- Jose

**Comment by vimal739** [comment]
Hi @peterlacour 
Great package btw, I use it for personal analysis of ticker symbols.
I've noticed when the program runs, it shows up "source: https://static.adsafeprotected.com/sca.17.5.11.js (32)" 
Wondering if this is a problem or why is this domain involved while running finpie

Thanks a bunch!
Vimal
